# Generated by Django 5.2.5 on 2026-01-16 04:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0015_utilisateurs_google_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
