# Generated by Django 5.2.5 on 2026-01-16 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0016_alter_produits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='profils',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
